# docker compose up -d --build

version: '3'

services:
  nginx1:
    build: .
    image: nginx1
    container_name: nginx1
    ports:
      - "80:80"
    networks:
      customnet:
        ipv4_address: 171.1.0.5

networks:
  customnet:
    external: true
