# docker compose up -d --build

version: '3'

services:
  ms2:
    build: .
    image: ms2
    container_name: ms2
    ports:
      - "3001:3001"
    networks:
      customnet:
        ipv4_address: 171.1.0.20

networks:
  customnet:
    external: true
